default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: zssn_development

test:
  <<: *default
  database: zssn_test

production:
  <<: *default
  database: zssn_production
  username: zssn
  password: <%= ENV['ZSSN_DATABASE_PASSWORD'] %>
